spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/imooc-demo
  session:
    store-type: none
  redis:
    database: 0
    host: localhost
    port: 6379
#security:
#  basic:
#    enabled: false